export const recipeImages: Record<string, any> = {
  "@/assets/images/recipeImages/spaghetti-bolognese.webp": require("@/assets/images/recipeImages/spaghetti-bolognese.webp"),
  "@/assets/images/recipeImages/curry.png": require("@/assets/images/recipeImages/curry.png"),
  "@/assets/images/recipeImages/tacos.png": require("@/assets/images/recipeImages/tacos.png"),
  "@/assets/images/recipeImages/vegetables.png": require("@/assets/images/recipeImages/vegetables.png"),
  "@/assets/images/recipeImages/pancakes.jpg": require("@/assets/images/recipeImages/pancakes.jpg"),
  "@/assets/images/recipeImages/grilled.png": require("@/assets/images/recipeImages/grilled.png"),
  "@/assets/images/recipeImages/salad.png": require("@/assets/images/recipeImages/salad.png"),
  "@/assets/images/recipeImages/soup.png": require("@/assets/images/recipeImages/soup.png"),
  "@/assets/images/recipeImages/rice.png": require("@/assets/images/recipeImages/rice.png"),
  "@/assets/images/recipeImages/cake.png": require("@/assets/images/recipeImages/cake.png"),
  "@/assets/images/recipeImages/omelette.png": require("@/assets/images/recipeImages/omelette.png"),
  "@/assets/images/recipeImages/burger.png": require("@/assets/images/recipeImages/burger.png"),
  "@/assets/images/recipeImages/pizza.png": require("@/assets/images/recipeImages/pizza.png"),
  "@/assets/images/recipeImages/greek.png": require("@/assets/images/recipeImages/greek.png"),
  "@/assets/images/recipeImages/sushi.png": require("@/assets/images/recipeImages/sushi.png"),
  "@/assets/images/recipeImages/lentil.png": require("@/assets/images/recipeImages/lentil.png"),
  "@/assets/images/recipeImages/thai.png": require("@/assets/images/recipeImages/thai.png"),
  "@/assets/images/recipeImages/pie.png": require("@/assets/images/recipeImages/pie.png"),
  "@/assets/images/recipeImages/guac.png": require("@/assets/images/recipeImages/guac.png"),
  "@/assets/images/recipeImages/chicken.png": require("@/assets/images/recipeImages/chicken.png"),
};
